/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTracesRouteImport } from './routes/app.traces'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRagAnalyticsRouteImport } from './routes/app.rag-analytics'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppExperimentsRouteImport } from './routes/app.experiments'
import { Route as AppEvaluationsRouteImport } from './routes/app.evaluations'
import { Route as AppDatasetsRouteImport } from './routes/app.datasets'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppTracesIdRouteImport } from './routes/app.traces.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesRoute = AppTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRagAnalyticsRoute = AppRagAnalyticsRouteImport.update({
  id: '/rag-analytics',
  path: '/rag-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationsRoute = AppEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesIdRoute = AppTracesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTracesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app/'
    | '/app/traces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app'
    | '/app/traces/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app/'
    | '/app/traces/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traces': {
      id: '/app/traces'
      path: '/traces'
      fullPath: '/app/traces'
      preLoaderRoute: typeof AppTracesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag-analytics': {
      id: '/app/rag-analytics'
      path: '/rag-analytics'
      fullPath: '/app/rag-analytics'
      preLoaderRoute: typeof AppRagAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments': {
      id: '/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluations': {
      id: '/app/evaluations'
      path: '/evaluations'
      fullPath: '/app/evaluations'
      preLoaderRoute: typeof AppEvaluationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets': {
      id: '/app/datasets'
      path: '/datasets'
      fullPath: '/app/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traces/$id': {
      id: '/app/traces/$id'
      path: '/$id'
      fullPath: '/app/traces/$id'
      preLoaderRoute: typeof AppTracesIdRouteImport
      parentRoute: typeof AppTracesRoute
    }
  }
}

interface AppTracesRouteChildren {
  AppTracesIdRoute: typeof AppTracesIdRoute
}

const AppTracesRouteChildren: AppTracesRouteChildren = {
  AppTracesIdRoute: AppTracesIdRoute,
}

const AppTracesRouteWithChildren = AppTracesRoute._addFileChildren(
  AppTracesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppEvaluationsRoute: typeof AppEvaluationsRoute
  AppExperimentsRoute: typeof AppExperimentsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppRagAnalyticsRoute: typeof AppRagAnalyticsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTracesRoute: typeof AppTracesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetsRoute: AppDatasetsRoute,
  AppEvaluationsRoute: AppEvaluationsRoute,
  AppExperimentsRoute: AppExperimentsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppRagAnalyticsRoute: AppRagAnalyticsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTracesRoute: AppTracesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
