/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTracesRouteImport } from './routes/app.traces'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRagAnalyticsRouteImport } from './routes/app.rag-analytics'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppGettingStartedRouteImport } from './routes/app.getting-started'
import { Route as AppExperimentsRouteImport } from './routes/app.experiments'
import { Route as AppEvaluationsRouteImport } from './routes/app.evaluations'
import { Route as AppDatasetsRouteImport } from './routes/app.datasets'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppTracesIdRouteImport } from './routes/app.traces.$id'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app.settings.api-keys'
import { Route as ApiAuthSignUpRouteImport } from './routes/api.auth.sign-up'
import { Route as ApiAuthSignOutRouteImport } from './routes/api.auth.sign-out'
import { Route as ApiAuthSignInRouteImport } from './routes/api.auth.sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesRoute = AppTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRagAnalyticsRoute = AppRagAnalyticsRouteImport.update({
  id: '/rag-analytics',
  path: '/rag-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationsRoute = AppEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesIdRoute = AppTracesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTracesRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/evaluations': typeof AppEvaluationsRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rag-analytics': typeof AppRagAnalyticsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/traces': typeof AppTracesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/traces/$id': typeof AppTracesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/getting-started'
    | '/app/insights'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/app/settings/api-keys'
    | '/app/traces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/getting-started'
    | '/app/insights'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/app/settings/api-keys'
    | '/app/traces/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/datasets'
    | '/app/evaluations'
    | '/app/experiments'
    | '/app/getting-started'
    | '/app/insights'
    | '/app/prompts'
    | '/app/rag-analytics'
    | '/app/settings'
    | '/app/traces'
    | '/app/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/app/settings/api-keys'
    | '/app/traces/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traces': {
      id: '/app/traces'
      path: '/traces'
      fullPath: '/app/traces'
      preLoaderRoute: typeof AppTracesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag-analytics': {
      id: '/app/rag-analytics'
      path: '/rag-analytics'
      fullPath: '/app/rag-analytics'
      preLoaderRoute: typeof AppRagAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/getting-started': {
      id: '/app/getting-started'
      path: '/getting-started'
      fullPath: '/app/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments': {
      id: '/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluations': {
      id: '/app/evaluations'
      path: '/evaluations'
      fullPath: '/app/evaluations'
      preLoaderRoute: typeof AppEvaluationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets': {
      id: '/app/datasets'
      path: '/datasets'
      fullPath: '/app/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traces/$id': {
      id: '/app/traces/$id'
      path: '/$id'
      fullPath: '/app/traces/$id'
      preLoaderRoute: typeof AppTracesIdRouteImport
      parentRoute: typeof AppTracesRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTracesRouteChildren {
  AppTracesIdRoute: typeof AppTracesIdRoute
}

const AppTracesRouteChildren: AppTracesRouteChildren = {
  AppTracesIdRoute: AppTracesIdRoute,
}

const AppTracesRouteWithChildren = AppTracesRoute._addFileChildren(
  AppTracesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppEvaluationsRoute: typeof AppEvaluationsRoute
  AppExperimentsRoute: typeof AppExperimentsRoute
  AppGettingStartedRoute: typeof AppGettingStartedRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppRagAnalyticsRoute: typeof AppRagAnalyticsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTracesRoute: typeof AppTracesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetsRoute: AppDatasetsRoute,
  AppEvaluationsRoute: AppEvaluationsRoute,
  AppExperimentsRoute: AppExperimentsRoute,
  AppGettingStartedRoute: AppGettingStartedRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppRagAnalyticsRoute: AppRagAnalyticsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTracesRoute: AppTracesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
